[component] 2013-04-20 10:21:25 INFO [main] com.lysoft.modules.component.Module.<init>(?) | initializing modulecomponent
[component] 2013-04-20 10:21:25 INFO [main] com.lysoft.modules.component.Module.start(?) | starting loading components....
[component] 2013-04-20 10:21:25 INFO [main] com.lysoft.modules.component.Module.start(?) | component:[test]loaded
[component] 2013-04-20 10:21:25 INFO [main] com.lysoft.modules.component.Module.start(?) | end loading components....
[component] 2013-04-20 10:21:26 INFO [main] com.lysoft.modules.component.Module.start_remote_service(?) | enable remote service provider
[component] 2013-04-20 10:21:27 ERROR [main] com.jenkov.template.JdbcTemplate.execute(?) | com.jenkov.db.itf.PersistenceException: Error determining primary key for table AES_USER
	at com.jenkov.db.impl.mapping.DbPrimaryKeyDeterminer.getPrimaryKeyMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidPrimaryKeyColumnName(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapSettersToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.createObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.generateObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.insert(Unknown Source)
	at com.web.master.component.test.butterfly.dao.impl.UserDaoImpl.add(UserDaoImpl.java:12)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:29)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:1)
	at com.jenkov.template.JdbcTemplate.doExecute(Unknown Source)
	at com.jenkov.template.JdbcTemplate.execute(Unknown Source)
	at com.lysoft.component.jdbc.butterfly.ButterflyTemplate.execute(Unknown Source)
	at com.web.master.component.test.service.user.UserService.add_user(UserService.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invokeSingleParam(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(Unknown Source)
	at com.lysoft.framework.core.service.AbstractService.invoke(Unknown Source)
	at com.lysoft.framework.common.service.ServiceUtils.invoke(Unknown Source)
	at com.web.master.component.test.user.ServiceTest.add(ServiceTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mas_test.aes_user' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2663)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1599)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3993)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3978)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:51)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3977)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	... 51 more

[component] 2013-04-20 10:21:27 ERROR [main] com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(?) | com.jenkov.db.scope.ScopeException: Error during transaction. Transaction aborted (rolled back). - Caused By: com.jenkov.db.itf.PersistenceException: Error determining primary key for table AES_USER
	at com.jenkov.db.scope.ScopingDataSource.abortTransactionScope(Unknown Source)
	at com.jenkov.template.JdbcTemplate.execute(Unknown Source)
	at com.lysoft.component.jdbc.butterfly.ButterflyTemplate.execute(Unknown Source)
	at com.web.master.component.test.service.user.UserService.add_user(UserService.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invokeSingleParam(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(Unknown Source)
	at com.lysoft.framework.core.service.AbstractService.invoke(Unknown Source)
	at com.lysoft.framework.common.service.ServiceUtils.invoke(Unknown Source)
	at com.web.master.component.test.user.ServiceTest.add(ServiceTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.jenkov.db.itf.PersistenceException: Error determining primary key for table AES_USER
	at com.jenkov.db.impl.mapping.DbPrimaryKeyDeterminer.getPrimaryKeyMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidPrimaryKeyColumnName(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapSettersToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.createObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.generateObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.insert(Unknown Source)
	at com.web.master.component.test.butterfly.dao.impl.UserDaoImpl.add(UserDaoImpl.java:12)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:29)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:1)
	at com.jenkov.template.JdbcTemplate.doExecute(Unknown Source)
	... 37 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mas_test.aes_user' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2663)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1599)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3993)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3978)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:51)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3977)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	... 51 more

[component] 2013-04-20 10:22:28 INFO [main] com.lysoft.modules.component.Module.<init>(?) | initializing modulecomponent
[component] 2013-04-20 10:22:28 INFO [main] com.lysoft.modules.component.Module.start(?) | starting loading components....
[component] 2013-04-20 10:22:28 INFO [main] com.lysoft.modules.component.Module.start(?) | component:[test]loaded
[component] 2013-04-20 10:22:28 INFO [main] com.lysoft.modules.component.Module.start(?) | end loading components....
[component] 2013-04-20 10:22:29 INFO [main] com.lysoft.modules.component.Module.start_remote_service(?) | enable remote service provider
[component] 2013-04-20 10:22:30 ERROR [main] com.jenkov.template.JdbcTemplate.execute(?) | com.jenkov.db.itf.PersistenceException: Error determining primary key for table KDB_USER
	at com.jenkov.db.impl.mapping.DbPrimaryKeyDeterminer.getPrimaryKeyMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidPrimaryKeyColumnName(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapSettersToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.createObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.generateObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.insert(Unknown Source)
	at com.web.master.component.test.butterfly.dao.impl.UserDaoImpl.add(UserDaoImpl.java:12)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:29)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:1)
	at com.jenkov.template.JdbcTemplate.doExecute(Unknown Source)
	at com.jenkov.template.JdbcTemplate.execute(Unknown Source)
	at com.lysoft.component.jdbc.butterfly.ButterflyTemplate.execute(Unknown Source)
	at com.web.master.component.test.service.user.UserService.add_user(UserService.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invokeSingleParam(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(Unknown Source)
	at com.lysoft.framework.core.service.AbstractService.invoke(Unknown Source)
	at com.lysoft.framework.common.service.ServiceUtils.invoke(Unknown Source)
	at com.web.master.component.test.user.ServiceTest.add(ServiceTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mas_test.kdb_user' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2663)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1599)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3993)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3978)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:51)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3977)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	... 51 more

[component] 2013-04-20 10:22:30 ERROR [main] com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(?) | com.jenkov.db.scope.ScopeException: Error during transaction. Transaction aborted (rolled back). - Caused By: com.jenkov.db.itf.PersistenceException: Error determining primary key for table KDB_USER
	at com.jenkov.db.scope.ScopingDataSource.abortTransactionScope(Unknown Source)
	at com.jenkov.template.JdbcTemplate.execute(Unknown Source)
	at com.lysoft.component.jdbc.butterfly.ButterflyTemplate.execute(Unknown Source)
	at com.web.master.component.test.service.user.UserService.add_user(UserService.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invokeSingleParam(Unknown Source)
	at com.lysoft.modules.component.service.invokeobj.MethodInvokeObject.invoke(Unknown Source)
	at com.lysoft.framework.core.service.AbstractService.invoke(Unknown Source)
	at com.lysoft.framework.common.service.ServiceUtils.invoke(Unknown Source)
	at com.web.master.component.test.user.ServiceTest.add(ServiceTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.jenkov.db.itf.PersistenceException: Error determining primary key for table KDB_USER
	at com.jenkov.db.impl.mapping.DbPrimaryKeyDeterminer.getPrimaryKeyMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidPrimaryKeyColumnName(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.assureValidObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapSettersToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.mapToTable(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.createObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.generateObjectMapping(Unknown Source)
	at com.jenkov.db.impl.mapping.ObjectMapper.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.getObjectMapping(Unknown Source)
	at com.jenkov.db.impl.ObjectDao.insert(Unknown Source)
	at com.web.master.component.test.butterfly.dao.impl.UserDaoImpl.add(UserDaoImpl.java:12)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:29)
	at com.web.master.component.test.service.user.UserService$1.doInConnection(UserService.java:1)
	at com.jenkov.template.JdbcTemplate.doExecute(Unknown Source)
	... 37 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mas_test.kdb_user' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2663)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1599)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3993)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3978)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:51)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3977)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getPrimaryKeys(DelegatingDatabaseMetaData.java:456)
	... 51 more

[component] 2013-04-20 10:24:23 INFO [main] com.lysoft.modules.component.Module.<init>(?) | initializing modulecomponent
[component] 2013-04-20 10:24:23 INFO [main] com.lysoft.modules.component.Module.start(?) | starting loading components....
[component] 2013-04-20 10:24:24 INFO [main] com.lysoft.modules.component.Module.start(?) | component:[test]loaded
[component] 2013-04-20 10:24:24 INFO [main] com.lysoft.modules.component.Module.start(?) | end loading components....
[component] 2013-04-20 10:24:25 INFO [main] com.lysoft.modules.component.Module.start_remote_service(?) | enable remote service provider
